#!/bin/sh

cd build

# if no build(s) specified, do all profile's builds!
[ $# -gt 0 ] && BUILDS="$@" || BUILDS=$(ls profile)

for B in $BUILDS
do
  BUILD="profile/$B"
  ( packer build -var-file=$BUILD/vars.json packer.json; echo $? >$BUILD/exit ) | tee $BUILD/output
  echo "=-> $(cat $BUILD/exit) <-="
done
